kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  namespace: app1
  name: "nginx-test-pl"
  labels:
    app: myapp1
spec:
  selector:
    matchLabels:
      name: "nginx-test-pl"
  template:
    metadata:
      labels:
        name: "nginx-test-pl"
        app: myapp1
    spec:
      containers:
        - name: "nginx-test"
          image: "nginx:1.7.9"
          ports:
            - containerPort: 80
              name: "porta1"
              protocol: TCP
  replicas: 1
