apiVersion: v1
kind: Service
metadata:
  name: nginx-test-pl
  namespace: app1
  labels:
    name: nginx-test-pl
    app: nginx-test-pl
spec:
  type: NodePort
  ports:
  - port: 80
    name: porta2
    protocol: TCP
    nodePort: 31080
    targetPort: 80
  selector:
    app:  nginx-test-pl
